name: tutorconnect
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  dropdown_search: ^5.0.0
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.0
  fluttertoast: ^8.2.1
  cloud_firestore: ^4.17.5
  
  image_picker: ^0.8.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/profile.png
    - assets/images/logo.png
    - assets/images/question.png
    - assets/images/home.png
